# Setup
title:            Luke Stringer
tagline:          'TAGLINE'
description:      'Engineering Manager and iOS Developer'
url:              http://lukestringer.me
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Luke Stringer'
  url:            https://twitter.com/lukestringer90

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
