# Setup
title:            Luke Stringer
tagline:          '@lukestringer90'
description:      'Engineering Manager and iOS Developer'
baseurl:          /
paginate:         5

# About and contact
author:
  name:           'Luke Stringer'
  url:            https://twitter.com/lukestringer90

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0


collections:
  notes:
      output: true
      sort_by: year