# Setup
title:            Luke Stringer
tagline:          '@lukestringer90'
description:      'Engineering Manager and iOS Developer'
paginate:         5

# About and contact
author:
  name:           'Luke Stringer'
  url:            https://twitter.com/lukestringer90

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

collections:
  notes:
      output: true
      sort_by: year
plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          
    id: UA-174388719-1     
    anonymizeIp: false 
